import Head from "next/head";
import Image from "next/image";
import styles from "../styles/productsDisplay.module.css";
import Link from "next/link";

export default function Home({ products }) {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Fel</h1>
      
    </div>
  )
}