import Head from "next/head";
import Image from "next/image";
import Link from "next/link";

export default function Error() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Error no page found</h1>
      
    </div>
  )
}