import Head from "next/head";
import Image from "next/image";
import { useEffect, useState } from "react";
import Item from "./products/[id]";

export default function Cart() {
  let [cart, setCart] = useState([]);
  const [totalPrice, setTotalPrice] = useState(0);

  let localCart;
  if (typeof window !== "undefined") {
    localCart = localStorage.getItem("cart");
  }

  //this is called on component mount
  useEffect(() => {
    //turn it into js
    localCart = JSON.parse(localCart);
    //load persisted cart into state if it exists
    if (localCart) setCart(localCart);
  }, []); //the empty array ensures useEffect only runs once

  useEffect(() => {
    let tempTotalPrice = 0;
    for (let index = 0; index < cart.length; index++) {
      // console.log(cart[index].price);
      tempTotalPrice =
        tempTotalPrice + cart[index].price * cart[index].quantity;
    }
    setTotalPrice(tempTotalPrice);
  }, [cart]);

  const makeChangesInLocalStorage = (newCart) => {
    let stringCart = JSON.stringify(newCart);
    localStorage.setItem("cart", stringCart);
  };

  const clearAll = () => {
    let cartCopy = [];
    setCart(cartCopy);
    makeChangesInLocalStorage(cartCopy);
  };

  const removeItem = (item) => {
    let cartCopy = [...cart];
    let objIndex = cart.findIndex((e) => e.title === item.title);
    // setCart(cart.filter((e) => e.title !== item.title));
    cartCopy.splice(objIndex, 1);
    setCart(cartCopy);
    makeChangesInLocalStorage(cartCopy);
  };

  const removeOneItem = (item) => {
    let cartCopy = [...cart];
    let objIndex = cart.findIndex((e) => e.title === item.title);
    cartCopy[objIndex].quantity--;
    if (cartCopy[objIndex].quantity <= 0) {
      removeItem(item);
    } else {
      setCart(cartCopy);
      makeChangesInLocalStorage(cartCopy);
    }
  };

  const addOneMoreItem = (item) => {
    let cartCopy = [...cart];
    let objIndex = cart.findIndex((e) => e.title === item.title);
    cartCopy[objIndex].quantity++;
    setCart(cartCopy);
    makeChangesInLocalStorage(cartCopy);
  };

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="m-8 p-4 max-w-md mx-auto bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl">
        <h1 className="mb-8 text-center font-semibold text-3xl">
          Shoppingcart!
        </h1>
        <div>
          {cart.map((item) => (
            <div key={item.id} className="flex flex-row  ">
              <div className="p-8 w-2/5 md:flex-shrink-0">
                <Image
                  width={170}
                  height={210}
                  src={item.image}
                  alt={item.image}
                />
              </div>
              <div className="mt-4 w-3/5  text-xl">
                <h4>{item.title}</h4>
                <h4 className="mt-2 font-semibold">Price: ${item.price.toFixed(2)}</h4>
                <div className="mt-6 flex justify-center space-x-1 ">
                  <button
                    className="py-2 px-4 bg-gray-500 text-white font-semibold rounded-lg shadow-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-opacity-75"
                    onClick={() => removeOneItem(item)}
                  >
                    -
                  </button>
                  <h6 className="bg-gray-200 w-12 text-center font-semibold rounded-lg ">
                    {item.quantity}
                  </h6>
                  <button
                    className=" py-2 px-4 bg-gray-500 text-white font-semibold rounded-lg shadow-md hover:bg-gray-700 focus:outline-none focus:ring-2 focus:ring-gray-400 focus:ring-opacity-75"
                    onClick={() => addOneMoreItem(item)}
                  >
                    +
                  </button>
                </div>
                <div className="mt-2 flex justify-center">
                  <button
                    className=" py-2 px-4 bg-red-400 text-white font-semibold rounded-lg shadow-md hover:bg-red-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75"
                    onClick={() => removeItem(item)}
                  >
                    Remove from cart
                  </button>
                </div>
              </div>
            </div>
          ))}
          <div className=" flex flex-col ">
            <h2 className="text-center font-semibold text-xl">
              Total price: ${totalPrice.toFixed(2)}
            </h2>
            <button
              className="py-2 px-4 bg-green-500 text-white font-semibold rounded-lg shadow-md hover:bg-green-700 focus:outline-none focus:ring-2 focus:ring-green-400 focus:ring-opacity-75"
              onClick={() => clearAll()}
            >
              Checkout
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
