import Head from "next/head";
import Image from "next/image";
import styles from "../styles/productsDisplay.module.css";
import Link from "next/link";

export default function Home({ products }) {
  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        {products.map((product) => (
          <Link key={product.id} href={`products/${product.id}`}>
            <div>
              <Image
                src={product.image}
                alt={product.image}
                width={200}
                height={200}
              />
              <h1>{product.title}</h1>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();

  return { props: { products: data } };
}
