import Head from "next/head";
import Image from "next/image";
import styles from "../styles/productsDisplay.module.css";
import Link from "next/link";
import { motion } from "framer-motion";

export default function Home({ products }) {
  const container = {
    hidden: { opacity: 1, scale: 0 },
    visible: {
      opacity: 1,
      scale: 1,
      transition: {
        when: "beforeChildren",
        staggerChildren: 0.1,
      },
    },
  };

  const item = {
    hidden: { y: 20, opacity: 0 },
    visible: { y: 0, opacity: 1 },
  };

  return (
    <div className={styles.main}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <div className="w-auto">
          <div className="grid justify-items-center">

            <motion.div animate={{ rotate: -360 }} transition={{ duration: 1 }}>
              <Image
                src="/FakeStoreLogo.PNG"
                alt="Fake store"
                width={400}
                height={400}
              />
            </motion.div>
            <motion.h2
              animate={{ rotate: 720 }}
              transition={{ duration: 3 }}
              className="mt-20 mb-8 text-4xl font-black"
            >
              Today´s offer
            </motion.h2>

          </div>
          <motion.div className="grid grid-cols-1 md:grid-cols-3 gap-8 w-50 min-w-full md:min-w-0  max-w-7xl mx-auto">
            {products.slice(0, 3).map((product) => (
              <Link key={product.id} href={`products/${product.id}`}>
                <motion.div
                  whileHover={{ scale: 1.1 }}
                  whileTap={{ scale: 0.9 }}
                  initial={{ opacity: 0 }}
                  animate={{ opacity: 1 }}
                  transition={{ duration: 5 }}
                  className=" opacity-80 hover:opacity-100 p-2 bg-white rounded-xl shadow-md overflow-hidden md:max-w-2xl grid justify-items-center"
                >
                  <Image
                    src={product.image}
                    alt={product.image}
                    width={170}
                    height={210}
                  />
                  <h3 className="text-2xl font-semibold">{product.title}</h3>
                  <p className="text-xl font-medium">Only ${product.price}</p>
                </motion.div>
              </Link>
            ))}
          </motion.div>
        </div>
      </div>
    </div>
  );
}

export async function getStaticProps() {
  const res = await fetch("https://fakestoreapi.com/products");
  const data = await res.json();

  return { props: { products: data } };
}
