import Head from "next/head";
import Image from "next/image";

export default function Shoppingcart() {
  let items = [{}];

  if (typeof window !== "undefined") {
    for (var i = 0; i <= localStorage.length; i++) {
      console.log(localStorage.getItem("product"));
      items.push(localStorage.getItem("product"));
    }
  }

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>Shoppingcart!</h1>

      {items.map((item) => (
        <div key={item}>
          <h2>{item.title}</h2>
        </div>
      ))}
    </div>
  );
}
